import { PlantaGEN } from "../interfaces";

export const plantasGEN: PlantaGEN[] = [
  { cia: "15", planta: "01", nombre: "Celaya" },
  { cia: "15", planta: "02", nombre: "Queretaro" },
  { cia: "15", planta: "03", nombre: "San Miguel de Allende" },
  { cia: "15", planta: "04", nombre: "Irapuato" },
  { cia: "15", planta: "06", nombre: "San Juan del Rio" },
  { cia: "15", planta: "07", nombre: "Dolores" },
  { cia: "15", planta: "08", nombre: "Xalapa" },
  { cia: "15", planta: "09", nombre: "Morelia" },
  { cia: "15", planta: "10", nombre: "Veracruz" },
  { cia: "15", planta: "12", nombre: "Acambaro" },
  { cia: "15", planta: "13", nombre: "San Jose Iturbide" },
  { cia: "15", planta: "14", nombre: "Lazaro Cardenas" },
  { cia: "15", planta: "15", nombre: "Uruapan" },
  { cia: "15", planta: "16", nombre: "La Piedad" },
  { cia: "15", planta: "17", nombre: "Salvatierra" },
  { cia: "15", planta: "18", nombre: "Moroleon" },
  { cia: "15", planta: "19", nombre: "Arandas" },
  { cia: "15", planta: "20", nombre: "Leon" },
  { cia: "15", planta: "21", nombre: "Monterrey" },
  { cia: "15", planta: "23", nombre: "San Luis Potosi" },
  { cia: "15", planta: "24", nombre: "Culiacan" },
  { cia: "15", planta: "25", nombre: "Mazatlan" },
  { cia: "15", planta: "26", nombre: "Guamuchil" },
  { cia: "15", planta: "27", nombre: "Los Mochis" },
  { cia: "15", planta: "28", nombre: "Tula" },
  { cia: "15", planta: "29", nombre: "Aguascalientes" },
  { cia: "15", planta: "65", nombre: "Tepatitlan" },
  { cia: "15", planta: "66", nombre: "Guadalajara" },
];
