import { PlantaGEN } from "../interfaces";

export const plantasGEN: PlantaGEN[] = [
  { cia: "15", planta: "01", nombre: "Celaya", server: "" },
  { cia: "15", planta: "02", nombre: "Queretaro", server: "" },
  { cia: "15", planta: "03", nombre: "San Miguel de Allende", server: "" },
  { cia: "15", planta: "04", nombre: "Irapuato", server: "" },
  { cia: "15", planta: "06", nombre: "San Juan del Rio", server: "" },
  { cia: "15", planta: "07", nombre: "Dolores", server: "" },
  { cia: "15", planta: "08", nombre: "Xalapa", server: "" },
  { cia: "15", planta: "09", nombre: "Morelia", server: "" },
  { cia: "15", planta: "10", nombre: "Veracruz", server: "" },
  { cia: "15", planta: "12", nombre: "Acambaro", server: "" },
  { cia: "15", planta: "13", nombre: "San Jose Iturbide", server: "" },
  { cia: "15", planta: "14", nombre: "Lazaro Cardenas", server: "" },
  { cia: "15", planta: "15", nombre: "Uruapan", server: "" },
  { cia: "15", planta: "16", nombre: "La Piedad", server: "" },
  { cia: "15", planta: "17", nombre: "Salvatierra", server: "" },
  { cia: "15", planta: "18", nombre: "Moroleon", server: "" },
  { cia: "15", planta: "19", nombre: "Arandas", server: "" },
  { cia: "15", planta: "20", nombre: "Leon", server: "" },
  { cia: "15", planta: "21", nombre: "Monterrey", server: "" },
  { cia: "15", planta: "23", nombre: "San Luis Potosi", server: "" },
  { cia: "15", planta: "24", nombre: "Culiacan", server: "" },
  { cia: "15", planta: "25", nombre: "Mazatlan", server: "" },
  { cia: "15", planta: "26", nombre: "Guamuchil", server: "" },
  { cia: "15", planta: "27", nombre: "Los Mochis", server: "" },
  { cia: "15", planta: "28", nombre: "Tula", server: "" },
  { cia: "15", planta: "29", nombre: "Aguascalientes", server: "" },
  { cia: "15", planta: "65", nombre: "Tepatitlan", server: "" },
  { cia: "15", planta: "66", nombre: "Guadalajara", server: "" },
];
